### ISSUE TITLE
Demo Map Corrupted

### ISSUE THREAD

**Issue by kiranmaya** [Giridharaprasath/ParkourGame#1]
Demo Map Corrupted, only alsv4 maps are working, also didn't find any new GameMode File to test the parkour Movements.

**Comment by Giridharaprasath** [comment]
Hi, Thanks for pointing it out. Fixed in e7e09e6537f54608fb7b5c576be298d518a5d6ed

**Comment by kiranmaya** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/3712631/195506254-a364cc58-a83d-4cec-ba47-2a852732971c.jpg)
still same message ,unable to open map

**Comment by Giridharaprasath** [comment]
Hi, So I figured out the issues, Its because of using Git LFS. I removed the files and reuploaded them. Hopefully it works correctly this time. Thank you for your continued interest.

**Comment by kiranmaya** [comment]
Everything is fine now.
